add Database migration script inculding destroy-environment and revert-migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,32 +8,37 @@ commands:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
       # Add parameter here   
+      workflow_id:
+        type: string
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            # Your code here
-            exit 1
+             if aws s3 ls | grep udapeople-<<parameters.workflow_id>>; then
+              aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
+            fi
+            aws cloudformation delete-stack --stack-name frontend-<<parameters.workflow_id>>
+            aws cloudformation delete-stack --stack-name backend-<<parameters.workflow_id>>
+      - revert-migrations:
+          workflow_id: <<parameters.workflow_id>>           
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      # Add parameter here
+      workflow_id:
+        type: string    
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            URL="https://blog.udacity.com/"
-            SUCCESS=curl -I ${URL} 2>/dev/null | head -n 1 | cut -d$' ' -f2 # test if website available
-            if(( $SUCCESS==200 )); 
-            then
-            cd ~/project/backend
-            npm install
-            else #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+            status=$(curl -H "token: <<parameters.workflow_id>>" \
+              --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>)
+            echo $status
+            if [[ "${status}" == 1 ]]; then
+              npm run migrations:revert
             fi
 
 jobs:  
@@ -218,8 +223,9 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
-
+      - destroy-environment: # Here's where you will add some code to rollback on failure      
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          when: on_fail
   configure-infrastructure:
     docker:
       - image: cimg/python:3.9.6 # Docker image here that supports Ansible
@@ -238,24 +244,56 @@ jobs:
           command: |
             ansible-playbook -i /tmp/.circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
       - destroy-environment: # Here's where you will add some code to rollback on failure 
-          workflow_id: "${CIRCLE_WORKFLOW_ID}"      
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          when: on_fail      
 
   run-migrations:
     docker:
       - image: circleci/node:13.8.0 # Docker image here that supports NodeJS
     steps:
       - checkout # Checkout code from git
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Creating .env for building backend environment
+          command: |
+            {
+              echo 'ENVIRONMENT=production'
+              echo 'VERSION=1'
+              echo 'TYPEORM_CONNECTION=postgres'
+              echo 'TYPEORM_MIGRATIONS_DIR=./src/migrations'
+              echo 'TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts'
+              echo 'TYPEORM_MIGRATIONS=./src/migrations/*.ts'
+              echo 'TYPEORM_HOST=${TYPEORM_HOST}'
+              echo 'TYPEORM_PORT=${TYPEORM_PORT}'
+              echo 'TYPEORM_USERNAME=${TYPEORM_USERNAME}'
+              echo 'TYPEORM_PASSWORD=${TYPEORM_PASSWORD}'
+              echo 'TYPEORM_DATABASE=${TYPEORM_DATABASE}'
+            } >> backend/.env
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            exit 1
+            sudo apt update
+            sudo apt install -y awscli
+            cd backend
+            cat .env
+            npm i
+            npm run build
+            npm run migrations 2>&1 | tee migrations-log.txt
       - run:
           name: Send migration results to memstash
           command: |
-            # Your code here
-            exit 1
-     # Here's where you will add some code to rollback on failure      
+            status_code="${PIPESTATUS[0]}"
+            if [[ ! "${status_code}" == 0 ]]; then
+              return 1
+            fi
+            if cat migration-log.txt | grep "has been executed successfully"; then
+              curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" \
+                --request PUT --data "1" \
+                https://api.memstash.io/values/migration-"${CIRCLE_WORKFLOW_ID}"
+            fi
+      - destroy-environment: # Here's where you will add some code to rollback on failure 
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"     
 
   deploy-frontend:
     docker:
@@ -276,7 +314,9 @@ jobs:
           name: Deploy frontend objects
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure      
+      - destroy-environment: # Here's where you will add some code to rollback on failure 
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          when: on_fail     
                     
   deploy-backend:
     docker:
@@ -293,7 +333,9 @@ jobs:
           name: Deploy backend
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure  
+      - destroy-environment: # Here's where you will add some code to rollback on failure 
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          when: on_fail 
 
   smoke-test:
     docker:
@@ -316,7 +358,9 @@ jobs:
           name: Frontend smoke test.
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure  
+      - destroy-environment: # Here's where you will add some code to rollback on failure 
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          when: on_fail 
 
   cloudfront-update:
     docker:
@@ -331,7 +375,9 @@ jobs:
           name: Update cloudfront distribution
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure  
+      - destroy-environment: # Here's where you will add some code to rollback on failure 
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          when: on_fail 
 
   cleanup:
     docker:
